apiVersion: apps/v1
kind: Deployment
metadata:
  name: lb-pods
  labels:
    app: lb-pods 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: lb-pods
  template:
    metadata:
      labels:
        app: lb-pods 
    spec:
      containers:
      - name: echo-hname
        image: sysnet4admin/echo-hname
---
apiVersion: v1
kind: Service
metadata:
  name: lb-svc 
spec:
  selector:
    app: lb-pods   
  ports:
    - name: http
      port: 80
      targetPort: 80 
  type: LoadBalancer

