apiVersion: v1
kind: Pod
metadata:
  name: net-conn-console
  labels:
    app: net-conn-console
    icmp: allow
spec:
  containers:
  - image: sysnet4admin/net-tools-ifn
    name: net
---
apiVersion: v1
kind: Pod
metadata:
  name: net-conn-allow
  labels:
    app: net-conn-allow
    icmp: allow
spec:
  containers:
  - image: sysnet4admin/net-tools-ifn
    name: net
---
apiVersion: v1
kind: Pod
metadata:
  name: net-conn-deny
  labels:
    app: net-conn-deny
    icmp: deny
spec:
  containers:
  - image: sysnet4admin/net-tools-ifn
    name: net
