apiVersion: v1
kind: Pod
metadata:
  name: tier-internet
  labels:
    icmp: allow
spec:
  containers:
  - image: sysnet4admin/net-tools-ifn
    name: tier
---
apiVersion: v1
kind: Pod
metadata:
  name: tier-intranet
  labels:
    icmp: allow
spec:
  containers:
  - image: sysnet4admin/net-tools-ifn
    name: tier
---
apiVersion: v1
kind: Pod
metadata:
  name: tier-privacy
  labels:
    icmp: deny
spec:
  containers:
  - image: sysnet4admin/net-tools-ifn
    name: tier
