apiVersion: v1
kind: Pod
metadata:
  name: workstation-internet
  labels:
    app: workstation-internet
    icmp: allow
spec:
  containers:
  - image: sysnet4admin/net-tools-ifn
    name: workstation
---
apiVersion: v1
kind: Pod
metadata:
  name: workstation-intranet
  labels:
    app: workstation-intranet
    icmp: allow
spec:
  containers:
  - image: sysnet4admin/net-tools-ifn
    name: workstation
---
apiVersion: v1
kind: Pod
metadata:
  name: workstation-privacy
  labels:
    app: workstation-privacy
    icmp: deny
spec:
  containers:
  - image: sysnet4admin/net-tools-ifn
    name: workstation
