apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ing-cl-default-svc
            port:
              number: 80
      - path: /hn
        pathType: Prefix
        backend:
          service:
            name: ing-cl-hname-svc
            port:
              number: 80
      - path: /ip 
        pathType: Prefix
        backend:
          service:
            name: ing-cl-ip-svc
            port:
              number: 80
