defaultRules:
  create: false
  rules:
    alertmanager: false

alertmanager:
  enabled: false

prometheus:
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.11
    port: 80
  prometheusSpec:
    storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: "managed-nfs-storage"
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: "8Gi"
    image:
      registry: prom
      repository: prometheus
      tag: v3.0.1
    version: v3.0.1
    scrapeInterval: "15s"
    evaluationInterval: "15s"

grafana:
  adminPassword: "admin"
  image:
    tag: "11.4.0"
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.12
  persistence:
    enabled: true
  grafana.ini:
    server:
      root_url: "http://192.168.1.12"

kubeEtcd:
  service:
    enabled: true
    port: 2381
    targetPort: 2381