grafana:
  enabled: true
  adminPassword: "admin"
  image:
    tag: "11.4.0"
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    storageClassName: "managed-nfs-storage"

tempo:
  enabled: true
  tempo:
    retention: 24h
  service:
    type: ClusterIP
  persistence:
    enabled: true
    storageClassName: "managed-nfs-storage"
