apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic-system
spec:
  version: 8.11.3
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: elastic-system
  http:
    service:
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.214
        ports:
        - name: web
          port: 80
          targetPort: 5601
  config:
    elasticsearch.requestHeadersWhitelist:
      - authorization
    server.publicBaseUrl: "http://192.168.1.214"
