apiVersion: batch/v1
kind: Job
metadata:
  name: job-chk-k8s
spec:
  template:
    spec:
      containers:
      - name: net-tools
        image: sysnet4admin/net-tools
        command: ["curlchk-k",  "kubernetes.default.svc.cluster.local/healthz"]
      restartPolicy: Never
