apiVersion: apps/v1
kind: Deployment
metadata:
  name: hpa
  labels:
    app: hpa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hpa
  template:
    metadata:
      labels:
        app: hpa
    spec:
      containers:
      - name: echo-hname
        image: sysnet4admin/echo-hname 
        resources:
          requests:
            cpu: "10m"
            memory: "5Mi"
          limits:
            cpu: "20m"
            memory: "10Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: lb-hpa 
spec:
  selector:
    app: hpa
  ports:
    - name: http
      port: 80
      targetPort: 80 
  type: LoadBalancer
