apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-gitops-nginx
  namespace: cicd
spec:
  project: default
  source:
    repoURL: 
    path: /
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
