#!/usr/bin/env bash

echo "=============================================="
echo " 7.4.2 블루그린(Blue-Green) 배포 실습"
echo "=============================================="
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📦 블루그린 배포 트리거"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  이미지를 변경하여 블루그린 배포 트리거:"
echo "   kubectl argo rollouts set image bluegreen-nginx nginx=nginx:1.27.3"
echo ""
echo "2️⃣  상태 확인:"
echo "   kubectl argo rollouts get rollout bluegreen-nginx --watch"
echo ""
echo "3️⃣  Preview 서비스로 새 버전 미리보기:"
PREVIEW_IP="$(kubectl get svc bluegreen-preview -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null)"
ACTIVE_IP="$(kubectl get svc bluegreen-active -o jsonpath='{.status.loadBalancer.ingress[0].ip}' 2>/dev/null)"
echo "   Active (현재):  http://$ACTIVE_IP"
echo "   Preview (신규): http://$PREVIEW_IP"
echo ""
echo "4️⃣  Preview에서 검증 후 전환 승격:"
echo "   kubectl argo rollouts promote bluegreen-nginx"
echo ""

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 블루그린 vs 롤링 업데이트"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  Deployment 롤링: 점진적 교체, 두 버전이 잠시 공존"
echo "  Rollout 블루그린: Preview로 검증 후 한 번에 전환"
echo "                   문제 시 즉시 롤백 가능 (Active 유지)"
