apiVersion: v1
kind: Pod
metadata:
  name: web-client-1
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: web-client-2
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: web-client-3
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: web-client-4
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: web-client-5
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: web-client-6
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: web-client-7
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: web-client-8
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: web-client-9
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
---
apiVersion: v1
kind: Pod
metadata:
  name: web-client-10
  labels:
    app: web-client
  annotations:
    policy.cilium.io/proxy-visibility: "<Egress/80/TCP/HTTP>"
spec:
  containers:
  - name: web-client
    image: sysnet4admin/net-tools-ifn
    command: ["/bin/sh", "-c"]
    args: ["while true; do curl -s --no-keepalive http://canary; sleep 1; done"]
