apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: canary-nginx
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: canary-nginx
  strategy:
    canary:
      steps:
      - setWeight: 25
      - pause: {}
      - setWeight: 50
      - pause: {duration: 30s}
      - setWeight: 75
      - pause: {duration: 30s}
  template:
    metadata:
      labels:
        app: canary-nginx
    spec:
      containers:
      - name: nginx
        image: sysnet4admin/dashboard:blue
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: 32Mi
          limits:
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: canary-nginx
spec:
  selector:
    app: canary-nginx
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
