apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
spec:
  version: 8.11.3
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: default
  http:
    service:
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.1.50
  config:
     elasticsearch.requestHeadersWhitelist:
     - authorization
  