# -*- mode: ruby -*-
# vi: set ft=ruby :

# each of components to install
k8s_V    = '1.36.0-1.1'                   # Kubernetes
ctrd_V   = '2.2.3-1~ubuntu.24.04~noble'  # Containerd
## /configuration variables ###

Vagrant.configure("2") do |config|

  #==============#
  # console Node #
  #==============#

  config.vm.define "console-k8s" do |cfg|
    cfg.vm.box = "sysnet4admin/Ubuntu-k8s"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "console-k8s(github_SysNet4Admin)"
      vb.cpus = 1
      vb.memory = 1024
      vb.customize ["modifyvm", :id, "--groups", "/Book-k8s-U#{k8s_V[0..5]}-ctrd-#{ctrd_V[0..2]}(github_SysNet4Admin)"]
    end
    cfg.vm.host_name = "console-k8s"
    cfg.vm.network "private_network", ip: "192.168.1.210"
    cfg.vm.network "forwarded_port", guest: 22, host: 60210, auto_correct: true, id: "ssh"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "k8s_con_pack.sh", args: [ k8s_V, k8s_V[0..3] ]
    cfg.vm.provision "file", source: "grab_kubeconfig.sh", destination: "/tmp/grab_kubeconfig.sh"
    cfg.vm.provision "shell", inline: "chmod 744 /tmp/grab_kubeconfig.sh ; mv /tmp/grab_kubeconfig.sh /root/grab_kubeconfig.sh" 
  end

end
