#!/usr/bin/env bash

echo "=============================================="
echo " 7.3.1 OTel 직접 연결 방식 분석"
echo "=============================================="
echo ""
echo "📋 HotROD 앱의 OTel 환경변수 확인:"
kubectl get deploy hotrod -o jsonpath='{range .spec.template.spec.containers[0].env[*]}{.name}={.value}{"\n"}{end}'
echo ""

echo "----------------------------------------------"
echo "⚠️  직접 연결 방식의 한계:"
echo "----------------------------------------------"
echo "1. 앱이 백엔드(Jaeger) 주소를 직접 알아야 함"
echo "   → OTEL_EXPORTER_OTLP_ENDPOINT=http://jaeger.monitoring:4318"
echo ""
echo "2. 백엔드를 교체하면 모든 앱의 환경변수를 수정해야 함"
echo "   → Jaeger → Tempo 교체 시 앱 재배포 필요"
echo ""
echo "3. 필터링, 샘플링 등 데이터 가공을 앱에서 처리해야 함"
echo "   → 앱 코드가 복잡해짐"
echo ""
echo "💡 해결 방법: OTel Collector를 중간에 두면"
echo "   앱 → Collector → 백엔드"
echo "   앱은 Collector 주소만 알면 되고, 백엔드 교체가 자유로움"
echo "   → 7.3.2에서 실습합니다."

echo ""
echo "----------------------------------------------"
echo "📊 현재 트레이스 확인:"
echo "----------------------------------------------"
JAEGER_IP="$(kubectl get svc jaeger -n monitoring -o jsonpath='{.status.loadBalancer.ingress[0].ip}')"
echo "Jaeger UI: http://$JAEGER_IP:16686"
echo ""
echo "📌 HotROD UI에서 버튼 클릭 후 Jaeger UI에서 확인하세요."
